project:
  type: book

book:
  title: "Completed"
  author: "Norah Jones"
  date: "2026/02/09"
  chapters:
    - index.qmd
    - Project_One.qmd
    - Day3_Prac_Q3andQ4.qmd
    - Practical_Day_Four.qmd
    

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt

editor: visual

